project_id = "rohpkchldzlubctuenwn"

[functions.check-price-alerts]
verify_jwt = false

[functions.analyze-product-page]
verify_jwt = false

[functions.check-price-drops]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.search-eshops]
verify_jwt = false

[functions.check-favorites-prices]
verify_jwt = false